apiVersion: v2
name: my-chart
description: A Helm chart for deploying ReplicaSet and kube-prometheus-grafana stack
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: kube-prometheus-stack
    version: "15.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"